# Change these first
owner: anduintransaction # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Anduin company landing page
    url: https://www.anduintransact.com
#  - name: Anduin company contact page
#    url: https://www.anduintransact.com/contact
  - name: Fundsub landing page
    url: https://www.fundsub.io
  - name: Fundsub contact page
    url: https://www.fundsub.io/contact
  - name: Anduin Dataroom landing page
    url: https://www.metadataroom.io/
  - name: Anduin Dataroom contact page
    url: https://www.metadataroom.io/contact
  - name: AnduinSign landing page
    url: https://www.anduinsign.io/
  - name: AnduinSign contact page
    url: https://www.anduinsign.io/contact
  - name: Anduin App login page
    url: "https://id.anduin.app/#/login"
  - name: Anduin App Deal main page
    url: "https://deals.anduin.app/"
  - name: Anduin App Dataroom main page
    url: "https://dataroom.anduin.app/"
  - name: Anduin App Sign main page
    url: "https://sign.anduin.app/"

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://avatars3.githubusercontent.com/u/8476311
  name: Anduin Transactions
  introTitle: "Website status and uptime monitoring"
  introMessage: This page publishes our most up-to-the-minute information on landing page availability below. Check back here any time to get current status information.
  navbar:
    - title: Status
      href: /
    - title: Anduin
      href: https://www.anduintransact.com/

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
