# Change these first
owner: anduintransaction # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Website
    url: https://anduintransact.com
    assignees:
      - andrew-anduin
      - msongd
      - victole-sec
  - name: Support page
    url: https://support.anduintransact.com/
    assignees:
      - msongd
      - victole-sec
  - name: Contact page
    url: https://anduintransact.com/contact
    assignees:
      - andrew-anduin
      - msongd
      - victole-sec
  - name: Authentication system
    url: "https://id.anduin.app/#/login"  
    assignees:
      - msongd
      - victole-sec
  - name: FundSub product status
    url: "https://fundsub.anduin.app/api/v3/standalone-app"
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{}'
    assignees:
      - msongd
      - victole-sec
  - name: Dataroom product status
    url: "https://dataroom.anduin.app/api/v3/standalone-app"
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{}'
    assignees:
      - msongd
      - victole-sec
  - name: eSign product status
    url: "https://sign.anduin.app/api/v3/standalone-app"
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{}'
    assignees:
      - msongd
      - victole-sec
  - name: RESTful API status
    url: https://api.anduin.app/api/v1/fundsub/docs/
    assignees:
      - msongd
      - victole-sec
  - name: GraphQL API status
    url: https://api.anduin.app/graphql
    headers:
      - "Content-Type: application/json"
    body: '{"query":"{queryFundSubscription(first: 10) {id orders(first: 100) { mainContact { id email } status } } }","operationName":null}'
    expectedStatusCodes:
      - 401
    assignees:
      - msongd
      - victole-sec
  - name: Test Secret Site
    url: $SECRET_SITE
    assignees:
      - msongd
      - victole-sec

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  cname: status.anduin.report
  #baseUrl: /upptime
  logoUrl: https://avatars3.githubusercontent.com/u/8476311
  name: Anduin Transactions System Status Report
  introTitle: "Website status and uptime monitoring"
  introMessage: This page publishes our most up-to-the-minute information on system availabilities. Check back here any time to get current status information.
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://anduintransact.com/
i18n:
  footer: This page is powered by [Upptime](https://upptime.js.org)
  
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
