# Change these first
owner: cmpham # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Anduin company landing page
    url: https://www.anduintransact.com
  - name: Fundsub landing page
    url: https://www.fundsub.io
  - name: Anduin Dataroom landing page
    url: https://www.metadataroom.io/
  - name: AnduinSign landing page
    url: https://www.anduinsign.io/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Anduin** landing page uptime monitor and status page, powered by Uptime & GitHub."
  introMessage: Monitor landing pages uptime
  navbar:
    - title: Status
      href: /
    - title: Anduin
      href: https://www.anduintransact.com/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
