# Change these first
owner: anduintransaction # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Anduin company landing page
    url: https://anduintransact.com
    assignees:
      - andrew-anduin
  - name: Support page
    url: https://support.anduintransact.com/
    assignees:
      - msongd
      - victole-sec
  - name: Anduin company contact page
    url: https://anduintransact.com/contact
    assignees:
      - andrew-anduin
  - name: Fundsub landing page
    url: https://fundsub.anduin.app/
    assignees:
      - msongd
      - victole-sec
  - name: Anduin Dataroom landing page
    url: https://dataroom.anduin.app/
    assignees:
      - msongd
      - victole-sec
  - name: AnduinSign landing page
    url: https://sign.anduin.app/
    assignees:
      - msongd
      - victole-sec
  - name: Anduin App login page
    url: "https://id.anduin.app/#/login"  
    assignees:
      - msongd
      - victole-sec
  - name: Anduin App Deal status
    url: "https://fundsub.anduin.app/api/v3/standalone-app"
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{}'
    assignees:
      - msongd
      - victole-sec
  - name: Anduin App Dataroom status
    url: "https://dataroom.anduin.app/api/v3/standalone-app"
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{}'
    assignees:
      - msongd
      - victole-sec
  - name: Anduin App Sign status
    url: "https://sign.anduin.app/api/v3/standalone-app"
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{}'
    assignees:
      - msongd
      - victole-sec

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://avatars3.githubusercontent.com/u/8476311
  name: Anduin Transactions
  introTitle: "Website status and uptime monitoring"
  introMessage: This page publishes our most up-to-the-minute information on landing page availability below. Check back here any time to get current status information.
  navbar:
    - title: Status
      href: /upptime/
    - title: Anduin
      href: https://anduintransact.com/

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
